id: d7_piwik_user_settings
label: Piwik user settings
migration_tags:
  - Drupal 7
source:
  plugin: d7_user
  constants:
    key: user_account_users
    module: piwik
process:
  uid: uid
  key: 'constants/key'
  module: 'constants/module'
  settings:
    # Based on skip_row_if_not_set
    plugin: matomo_skip_row_if_not_set
    key: custom
    module: matomo
    source: data
destination:
  plugin: user_data
migration_dependencies:
  required:
    - d7_user
