id: d7_piwik_settings
label: Piwik 7 configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - piwik_cache
    - piwik_codesnippet_after
    - piwik_codesnippet_before
    - piwik_custom
    - piwik_custom_var
    - piwik_domain_mode
    - piwik_pages
    - piwik_privacy_donottrack
    - piwik_roles
    - piwik_site_id
    - piwik_site_search
    - piwik_trackmessages
    - piwik_track
    - piwik_trackfiles_extensions
    - piwik_trackmailto
    - piwik_trackuserid
    - piwik_translation_set
    - piwik_url_http
    - piwik_url_https
    - piwik_visibility
    - piwik_visibility_roles
    - piwik_page_title_hierarchy
    - piwik_page_title_hierarchy_exclude_home
process:
  cache: piwik_cache
  'codesnippet/after': piwik_codesnippet_after
  'codesnippet/before': piwik_codesnippet_before
  'custom/variable': piwik_custom_var
  domain_mode: piwik_domain_mode
  'privacy/donottrack': piwik_privacy_donottrack
  site_id: piwik_site_id
  'track/files': piwik_track
  'track/files_extensions': piwik_trackfiles_extensions
  'track/mailto': piwik_trackmailto
  'track/messages': piwik_trackmessages
  'track/site_search': piwik_site_search
  'track/userid': piwik_trackuserid
  'translation_set': piwik_translation_set
  url_http: piwik_url_http
  url_https: piwik_url_https
  'visibility/custom': piwik_custom
  'visibility/pages': piwik_pages
  'visibility/pages_enabled': piwik_visibility
  'visibility/roles': piwik_roles
  'visibility/roles_enabled': piwik_visibility_roles
  page_title_hierarchy: piwik_page_title_hierarchy
  page_title_hierarchy_exclude_home: piwik_page_title_hierarchy_exclude_home
destination:
  plugin: config
  config_name: piwik.settings
dependencies:
  module:
    - piwik
    - migrate_drupal
